# CSS Selectors for GBF
# Update these if game UI changes

quest:
  summonScreen: '.prt-supporter-list'
  summonSlot1: '.lis-supporter:nth-child(1) .btn-supporter-use'
  summonSlot2: '.lis-supporter:nth-child(2) .btn-supporter-use'
  summonSlot3: '.lis-supporter:nth-child(3) .btn-supporter-use'
  startQuestButton: '.btn-usual-ok'

battle:
  battleScreen: '.prt-battle-window'
  attackButton: '.btn-attack-start'
  fullAutoButton: '.btn-auto'
  autoButton: '.btn-auto'
  skillRail: '.prt-ability-rail-overlayer' # Added for FA detection
  attackCancel: '.btn-attack-cancel'
  captchaPopup: '.pop-usual.common-pop-error.pop-show'
  captchaHeader: '.prt-popup-header'
  turnCounter: '#js-turn-num-count'
  turnDigits: '#js-turn-num-count > div'
  resultScreen: '.prt-result'
  okButton: '.pop-usual.pop-exp.pop-show .btn-usual-ok'
  emptyResultNotice: '.txt-empty-notice'
  nextButton: '.btn-usual-next'
  closeButton: '.btn-usual-close'

raid:
  raidBackupUrl: 'https://game.granbluefantasy.jp/#quest/assist'
  raidList: '.prt-raid-list'
  raidEntry: '.btn-multi-raid.lis-raid.search'
  joinButton: '.btn-raid-join'
  backupRequestButton: '.btn-backup-request'
  errorPopup: '.prt-popup-footer .btn-usual-ok'
  unclaimedRaidUrl: 'https://game.granbluefantasy.jp/#quest/assist/unclaimed/0/0'
  unclaimedRaidEntry: '.btn-multi-raid.lis-raid'
  raidEndedPopup: '.pop-result-assist-raid.pop-show'
  raidEndedOkButton: '.pop-result-assist-raid.pop-show .btn-usual-ok'
  maxRaidsPopup: '.common-pop-error'
  maxRaidsOkButton: '.common-pop-error .btn-usual-ok'

replicard:
  nodeMap: '.prt-replicard-map'
  node: '.map-node'
  startButton: '.se-quest-start'
  startWrapper: '.pop-deck.supporter'

login:
  loginButton: '#login-auth'
  mobageOption: '#mobage-login'
  emailField: '#subject-id'
  passwordField: '#subject-password'
  submitButton: '#login'
  closeButton: '.btn-inner.w-btn-m'
